### ISSUE TITLE
Custom Shaders

### ISSUE THREAD

**Issue by UstymUkhman** [tchayen/red-otter#12]
Hi @tchayen! Really interesting project, thanks for working on it.
I've briefly checked some examples and would like to know if there's a way to inject some custom shaders in order to apply some postprocessing after the base layout has been drawn? If not, what do think about this feature? Are there any plans to work on it in the future?

**Comment by tchayen** [comment]
Hi! Currently there's no way to do that. But…

I am working on a big rewrite of almost everything (a bit like version 2.0 but in this case from 0.0.16 it will become uhm, 0.1?). I haven't made any plans to add custom shaders yet but I think it makes a lot of sense. I will keep thinking about it and hopefully when I am done with other things I will have some good idea for it.

Thanks for bringing this up, it's a great idea!

**Comment by UstymUkhman** [comment]
Cool! Looking forward to this v0.1 then. Thanks again for working on it!
