### ISSUE TITLE
Running into trouble with jsx-runtime

### ISSUE THREAD

**Issue by tanishqkancharla** [tchayen/red-otter#7]
Hello! I keep running into this issue (using parcel@2.8 and typescript@4.6). This is the error I see when hovering over any JSX in vscode. If I compile with typescript on the cli, I also get the same error.

```
Cannot find module 'red-otter/jsx-runtime' or its corresponding type declarations.ts(2307)
```

If I compile with parcel, I see this:
```
🚨 Build failed.

@parcel/core: Failed to resolve 
'red-otter/jsx-dev-runtime' from 
'./src/index.tsx'

  /Users/tanishqkancharla/Documents/Projects/webgl-editor/src/index.tsx:1:1
  > 1 | import { Context, Font, FontAt
  >   | ^
    2 | 
    3 | async function loadFont(fontUr
```

This might be related to the `exports` field in your package.json which leaves out jsx-runtime?

My `.parcelrc`:
```json
{
	"extends": "@parcel/config-default",
	"transformers": {
		"url:*": ["@parcel/transformer-raw"]
	}
}
```

`index.tsx`:
```tsx
import { Context, Font, FontAtlas, Layout, TTF } from "red-otter";

async function loadFont(fontUrl: string) {
	// Add font to the document so we will use browser to rasterize the font.
	const fontFace = new FontFace("Inter", `url("${fontUrl}")`);
	await fontFace.load();
	document.fonts.add(fontFace);

	// Download font file for parsing.
	const file = await fetch(fontUrl);
	const buffer = await file.arrayBuffer();

	const ttf = new TTF(buffer);
	if (!ttf.ok) {
		throw new Error("Failed to parse font file.");
	}

	// Render font atlas.
	const atlas = new FontAtlas(ttf);
	const { canvas, spacing } = atlas.render();

	const image = new Image();
	image.src = canvas.toDataURL();

	return new Font(spacing, image);
}

export function add(x: number, y: number) {
	return x + y;
}

async function run() {
	const canvas = document.createElement("canvas");
	const scale = window.devicePixelRatio;
	canvas.width = 800 * scale;
	canvas.height = 600 * scale;

	const div = document.getElementById("app")!;
	div.appendChild(canvas);

	const font = await loadFont("./inter.ttf");

	const context = new Context(canvas, font);
	context.clear();

	const layout = new Layout(context);
	layout.add(
		<view style={{ width: 100, height: 100, backgroundColor: "#fff" }}>
			<text style={{ fontFamily: font, fontSize: 20, color: "#000" }}>
				Hello
			</text>
		</view>
	);

	layout.render();
	context.flush();
}

if (typeof window !== "undefined") {
	// If in browser context
	run();
}
```

Relevant of `package.json`:
```json
"type": "module",
	"scripts": {
		"build": "parcel src/index.html",
		"dev": "parcel src/index.html",
		"serve": "parcel serve dist",
		"deploy": "npx vercel deploy",
		"test": "NODE_OPTIONS='--loader tsx' mocha './src/**/*.test.ts' --verbose"
	},
```

`tsconfig.json`
```json
{
	"compilerOptions": {
		"jsx": "react-jsx",
		"jsxImportSource": "red-otter",
		"types": ["red-otter", "./src/types"],
		"target": "es2017",
		"module": "ESNext" /* Specify what module code is generated. */,
		"esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */,
		"forceConsistentCasingInFileNames": true /* Ensure that casing is correct in imports. */,
		"moduleResolution": "node",

		/* Type Checking */
		"strict": true /* Enable all strict type-checking options. */,
		"skipLibCheck": true /* Skip type checking all .d.ts files. */,
		"outDir": "dist"
	},
	"include": ["./src/**.ts"]
}
```

Any tips you might have would be greatly appreciated :)

**Comment by tchayen** [comment]
For now the lib doesn't support the new jsx transforms (`"jsx": "react-jsx"`, React [blog post](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) about them) but the old one:

```
"jsx": "react",
"jsxFactory": "jsx"
```

I was able to reproduce the problem and it went away once I changed those two lines so I hope this will solve it.

If you have some particular reason to use the new transform – let me know.

I started working on it some time ago but it was quite tedious and not very satisfying (to spend who knows how much more time just to get to work something that already works 😅).

But of course I am happy to eventually add support for it if there's a demand for that!

**Comment by tanishqkancharla** [comment]
Oh sweet that works! I swear the documentation told me to try what I did first, but I'm looking at it now and it says your recommendation. I'm not super familiar with the nuance between old and new jsx transform. Is there anyway to avoid the `jsx` import in each file? Can I point typescript to the right file somewhere?

**Comment by tchayen** [comment]
I think this is why `import React from 'react'` used to be necessary in each file with JSX and how it's not needed anymore because TypeScript now 'knows' where to import it from. It definitely looks useful.

I will look into adding support for this as soon as I have more time to play with it.

**Comment by tanishqkancharla** [comment]
I looked into this a little bit. It seems simpler than I initially thought. You might need to publish a separate `jsx-runtime` package though? Here is the PR diff: https://github.com/tchayen/red-otter/compare/main...tanishqkancharla:red-otter:main?expand=1

So:
* Vite looks at jsx, resolves to `red-otter/jsx-runtime`
* It also uses the alias I defined in vite.config, which resolves to `./src/jsx-runtime`.
* Typescript complains here though, because it doesn't understand the alias; it can't find the jsx types of that import.
* I also updated the package.json exports which should let packages depending on it try out the new jsx transform. I couldn't try this out though.

**Comment by tchayen** [comment]
Thanks so much for looking into this, that's all I needed and more!

In theory `red-otter/jsx-runtime` should be the same as just `red-otter/jsx-runtime.js` when added to `package.json` > `exports` > `jsx-runtime` (or at least for ESM, not sure if for UMD).

I will do my best to allocate some time for this within a week. Thanks again!
